### ISSUE TITLE
Model field using PhoneField is not recognized in a ModelForm

### ISSUE THREAD

**Issue by flvyu** [VeryApt/django-phone-field#10]
I have created a model with a phone_number field like the following:

```
phone_number = PhoneField(blank=False, help_text='Contact Number')
```

However when I use this model to create a ModelForm, the form has an error when `is_valid` is called saying that phone number is required even though the data is passed to the request. All the other fields that are required work fine.

**Ex:**
```
class ApplicationForm(ModelForm):
    class Meta:
        model = Application
        fields = ['first_name', 'last_name', 'email', 'phone_number']
```

**Environment:**
django 3.0
Python 3

**Comment by va-andrew** [comment]
I created a ModelForm view along the lines you mention: b17e83e8372ac509bf2bf61ba452aed0d1e1e17f 

However, I am unable to replicate this with Django 3.0. Can you create a fork with an example?

**Comment by flvyu** [comment]
I also could not reproduce it using the fork I made of the branch. However, still having the issue on the other application.

**Comment by va-andrew** [comment]
Ah okay. I'm closing this issue for now, feel free to reopen if you can reproduce it with our test project.

**Comment by Radilx** [comment]
Just wanted to say -- I was having similar issues. You have to use `{{ form.phone }}`, you can't try to do things like constructing your own custom form and extracting `{{ form.phone.id_for_label}}`. My client page was sending `phone` in the post request instead of `phone_0` and `phone_1` like the ModelForm was expecting.
