### ISSUE TITLE
How can I access to the area code form my defined phoneField?

### ISSUE THREAD

**Issue by agustin-jimenez** [VeryApt/django-phone-field#16]
Hi! I want some help.  I need getting the area code from a defined PhoneField() on my model. Is it possible?

**Comment by va-andrew** [comment]
I would look at `PhoneNumber.cleaned`, which will give you a number expressed as `+13335556666`. From there, you can take characters 2-4 to extract the area code part -> `my_number.cleaned[2:5]`.

**Comment by agustin-jimenez** [comment]
Thank you a lot!
