### ISSUE TITLE
PhoneWidget size attrs

### ISSUE THREAD

**Issue by dwasyl** [VeryApt/django-phone-field#5]
Since `PhoneWidget` updates the `phone_attrs` and `ext_attrs` based on the `attrs` provided to the widget there is no runtime way of lengthening just the `phone_attrs` or `ext_attrs` input boxes. Currently to change the length of one, you must change the length of both inputs.

Would you be open to separate `attrs` value of `phone_size` and `ext_size` that then get applied to the respective `attr` default `size`?

**Comment by va-andrew** [comment]
Yeah, that's a good idea. Feel free to submit a PR, or I can get to this later in the week

**Comment by dwasyl** [comment]
Okay, I will see if I have time. I'm busy trying to shoehorn `PhoneWidget` into `crispy-forms` which is an adventure on its own.
