### ISSUE TITLE
Disable Extension

### ISSUE THREAD

**Issue by CamGenius** [VeryApt/django-phone-field#8]
It would be great if you could disable the extension in the form.

**Comment by va-andrew** [comment]
It wouldn't be hard to add that to `PhoneFormField`, but would it be any better than simply hiding the extension input via CSS? In the latter case, you don't risk clobbering an existing extension if one somehow winds up in your database.

**Comment by abraner** [comment]
I have used the "display:none;" in my CSS to hide the extension input but the "ext." text is still there. Is there a way to hide that as well?

**Comment by va-andrew** [comment]
Looks like there isn't a great way to do that. Perhaps we should wrap the "ext." text in a `span` so it can be selected and hidden.

**Comment by va-andrew** [comment]
Resolved in 1.8.0 release: now you can also specify

`.phone-field-ext { display: none; }`

**Comment by abraner** [comment]
Great! Thank you.

**Comment by szpm102** [comment]
Hi.. in Django where exactly do I specify to remove the extension part please? In django forms or django models?

**Comment by chidiohiri** [comment]
> Hi.. in Django where exactly do I specify to remove the extension part please? In django forms or django models?

This would be in CSS
