### ISSUE TITLE
django-crispy-forms

### ISSUE THREAD

**Issue by 5starkarma** [VeryApt/django-phone-field#9]
Any plans to make work with django-crispy-forms?

**Comment by awmack** [comment]
It's not on our roadmap, but would consider a pull request if it was only a minor change. I don't use `django-crispy-forms` so I'm not sure what supporting it would entail.

**Comment by 5starkarma** [comment]
I tried it out and it looks like a sweet little app but crispy didnt handle it.  I will take a look into it if I get time. Thanks for the response.
